// api/_words.js — Curated German "Word of the Day" pool.
//
// 150 words focused on expat daily-life utility — things you'll actually
// encounter living in Berlin. Mix of:
//   - True German vocabulary with cultural weight (Feierabend, Schadenfreude)
//   - Bureaucracy compound nouns (Anmeldung, Wohnungsgeberbestätigung)
//   - Berlin-specific terms (Späti, Kiez, BVG slang)
//   - Useful daily phrases (Mahlzeit, Tschüss, etc.)
//
// generateExtras picks one at random per send, avoiding recently used.
// 150 entries / 1 per day = 5-month rotation before repeat.
//
// Schema per entry:
//   german:  the word/phrase
//   literal: literal/etymological translation (optional, omit if N/A)
//   meaning: actual usage meaning
//   example: short usage example (optional but recommended)
//
// To add: append to WORDS array. Check no duplicates first.

var WORDS = [
  { german: "Feierabend", literal: "celebration evening", meaning: "the end of the workday", example: "\"Schönen Feierabend!\" — said to colleagues leaving work, even on a Tuesday." },
  { german: "Anmeldung", literal: "registration", meaning: "the mandatory address registration at the Bürgeramt within 14 days of moving", example: "You can't open a bank account, get a tax ID, or sign a phone contract without proof of Anmeldung." },
  { german: "Späti", literal: "late-shop", meaning: "a small late-night corner store, beloved Berlin institution", example: "\"Bier vom Späti\" — the way most Berliners start a Friday evening." },
  { german: "Kiez", literal: "neighborhood", meaning: "your immediate area — typically just a few blocks where you know the bakery, café, and people", example: "\"In meinem Kiez\" carries more local pride than \"in my neighborhood\" ever does." },
  { german: "Schadenfreude", literal: "harm-joy", meaning: "pleasure at someone else's misfortune", example: "Watching a tourist try and fail to pronounce \"Schöneberg\" — a tiny Schadenfreude moment." },
  { german: "Doch", literal: "yet/but", meaning: "an emphatic contradiction — used to disagree with a negative statement", example: "\"You don't like döner?\" \"Doch!\" — meaning yes, I actually do." },
  { german: "Gemütlich", literal: "comfortable/cozy", meaning: "warm, relaxed, comfortably social — the German cousin of Danish hygge", example: "A gemütlich café has soft lighting, no rush, and serves cake at 4pm without judgment." },
  { german: "Mahlzeit", literal: "mealtime", meaning: "greeting used around lunch, even if you're not eating", example: "Walk into any German office between 11:30 and 14:00 — \"Mahlzeit\" is the only acceptable greeting." },
  { german: "Tschüss", literal: "bye", meaning: "casual goodbye, all-purpose", example: "Said at the end of every transaction, from buying bread to leaving a doctor's office." },
  { german: "Pfand", literal: "deposit", meaning: "the bottle/can deposit (€0.08–0.25) refunded at supermarkets", example: "Berlin's homeless economy quietly runs on Pfand — leave your bottles next to the bin, not in it." },
  { german: "Bürgeramt", literal: "citizen office", meaning: "the registration office where you do all official paperwork", example: "Getting a Bürgeramt Termin in Berlin requires either patience, luck, or a 6am refresh-bot." },
  { german: "Wohnungsgeberbestätigung", literal: "apartment-giver confirmation", meaning: "the landlord's signed confirmation of your residence — required for Anmeldung", example: "Your future landlord must give you this document. No Wohnungsgeberbestätigung means no Anmeldung." },
  { german: "Termin", literal: "appointment", meaning: "the appointment slot for everything in Germany — doctor, Bürgeramt, dentist, bank", example: "\"Ich brauche einen Termin\" — phrase you'll say more in Berlin than \"How are you?\"" },
  { german: "Krankenkasse", literal: "sick-fund", meaning: "your statutory health insurance fund", example: "Your Krankenkasse covers most healthcare costs, but you'll still get bills you don't expect." },
  { german: "Steuererklärung", literal: "tax declaration", meaning: "the annual tax return — usually voluntary but often results in a refund", example: "Most German employees skip Steuererklärung; the ones who file get an average €1,063 back." },
  { german: "Quittung", literal: "receipt", meaning: "a receipt — always ask for one, you'll need it later", example: "\"Quittung, bitte\" — habit worth building, especially for work expenses." },
  { german: "Stoßzeit", literal: "push-time", meaning: "rush hour on transit", example: "The U7 at 8:15am Stoßzeit is its own kind of Berlin character-building exercise." },
  { german: "Pendeln", literal: "to swing/commute", meaning: "to commute, usually long-distance", example: "Berlin-Brandenburg pendeln has become a daily reality for thousands priced out of the city." },
  { german: "Bahnhof", literal: "train station", meaning: "train station; also slang for \"I don't understand a word\"", example: "\"Ich verstehe nur Bahnhof\" — said when a conversation switches to fluent German and you're lost." },
  { german: "Hauptbahnhof", literal: "main train station", meaning: "the central train station — Berlin's is Europe's largest crossing station", example: "Berlin Hauptbahnhof opened in 2006 and stacks three train levels in one building." },
  { german: "S-Bahn", literal: "Stadtschnellbahn — city express rail", meaning: "the suburban rail network, distinct from the U-Bahn", example: "S-Bahn runs above ground mostly; U-Bahn runs underground (mostly)." },
  { german: "Schwarzfahren", literal: "black-riding", meaning: "riding transit without a valid ticket", example: "Berlin doesn't have ticket gates — but plain-clothes controllers do exist. The fine is €60." },
  { german: "Hausmeister", literal: "house-master", meaning: "the building caretaker — handles repairs, garbage, mail issues", example: "Befriend your Hausmeister. They'll fix things faster than your landlord ever will." },
  { german: "Nebenkosten", literal: "side-costs", meaning: "the additional building costs on top of rent — heating, water, building maintenance", example: "\"Kaltmiete\" is rent without Nebenkosten; \"Warmmiete\" includes them. Always ask which one." },
  { german: "Kaltmiete", literal: "cold rent", meaning: "rent excluding heating and utilities", example: "Listed prices usually quote Kaltmiete. Add roughly 25% for the real monthly cost." },
  { german: "Warmmiete", literal: "warm rent", meaning: "rent including heating and basic utilities", example: "Warmmiete is the honest number to budget against." },
  { german: "Kaution", literal: "deposit/bail", meaning: "rental deposit — up to 3 months' Kaltmiete, held in a separate account", example: "Get the Kaution paid into a Mietkautionskonto, not your landlord's personal account." },
  { german: "Wohngemeinschaft", literal: "living-community", meaning: "shared apartment (WG) — the standard living arrangement for under-30 Berliners", example: "WG-Casting is real: a roommate \"interview\" where 8 candidates are graded over wine." },
  { german: "Mietspiegel", literal: "rent mirror", meaning: "the official rent index — sets legal upper limits on rent increases", example: "Berlin's Mietspiegel updates every two years and decides whether your landlord can raise rent." },
  { german: "Nebensaison", literal: "side-season", meaning: "off-peak season for travel/tourism", example: "Berlin's Nebensaison runs November to March — cheaper flats, fewer tourists, more weltschmerz." },
  { german: "Weltschmerz", literal: "world-pain", meaning: "philosophical sadness about the state of the world", example: "Weltschmerz peaks in February in Berlin, when the sky has been grey for 73 consecutive days." },
  { german: "Fernweh", literal: "far-pain", meaning: "longing for distant places — the opposite of homesick", example: "Fernweh hits hardest at Tegel-era flight noises." },
  { german: "Heimweh", literal: "home-pain", meaning: "homesickness", example: "First Heimweh usually arrives around month 4 of expat life." },
  { german: "Ohrwurm", literal: "ear-worm", meaning: "a song stuck in your head", example: "\"99 Luftballons\" is a national Ohrwurm — once heard, never escaped." },
  { german: "Kummerspeck", literal: "grief-bacon", meaning: "weight gained from emotional overeating", example: "Post-breakup Kummerspeck is the universal currency of human resilience." },
  { german: "Treppenwitz", literal: "staircase-joke", meaning: "the perfect comeback you think of only after the moment has passed", example: "Standard German Treppenwitz: realizing the perfect response halfway home on the U2." },
  { german: "Fingerspitzengefühl", literal: "fingertip-feeling", meaning: "tact; sensitivity to nuance", example: "Negotiating with German bureaucracy requires Fingerspitzengefühl — push too hard and you start over." },
  { german: "Innerer Schweinehund", literal: "inner pig-dog", meaning: "the inner voice telling you to skip the gym", example: "The morning struggle with your innerer Schweinehund is universal." },
  { german: "Bildungslücke", literal: "education-gap", meaning: "an embarrassing gap in your general knowledge", example: "Admitting your Bildungslücke about Goethe is more respected than faking it." },
  { german: "Verschlimmbessern", literal: "to worsen-improve", meaning: "to make something worse by trying to improve it", example: "Every IKEA assembly project has at least one Verschlimmbessern moment." },
  { german: "Backpfeifengesicht", literal: "slap-whistle-face", meaning: "a face that begs to be slapped", example: "An untranslatable but oddly satisfying word — applied at your own discretion." },
  { german: "Sitzfleisch", literal: "sitting-meat", meaning: "the ability to endure long meetings or hard work through sheer persistence", example: "German Beamte (civil servants) are selected for Sitzfleisch above all other qualities." },
  { german: "Drachenfutter", literal: "dragon-food", meaning: "a peace offering — flowers or chocolates after a fight", example: "Sunday flower shops at train stations exist almost entirely for Drachenfutter." },
  { german: "Geisterfahrer", literal: "ghost-driver", meaning: "someone driving the wrong way down a highway", example: "ARD radio gives Geisterfahrer alerts during traffic news. Treat as serious safety information." },
  { german: "Stammtisch", literal: "regulars' table", meaning: "the reserved table at a pub where the same people meet weekly", example: "Most German neighborhoods still have a Stammtisch — usually Thursdays, usually political." },
  { german: "Gleichberechtigung", literal: "equal-justification", meaning: "equality of rights, especially gender equality", example: "Article 3 of the Grundgesetz guarantees Gleichberechtigung — the word predates much of the global feminist movement." },
  { german: "Datenschutz", literal: "data-protection", meaning: "data privacy — Germans take it more seriously than most cultures", example: "Datenschutz is why your German colleagues will refuse to be tagged in photos online." },
  { german: "Putzfimmel", literal: "cleaning-mania", meaning: "obsessive cleanliness", example: "Saturday morning Putzfimmel is a German cultural ritual — vacuums at 8am are not a noise complaint, they're tradition." },
  { german: "Wanderlust", literal: "hike-desire", meaning: "the urge to travel/hike", example: "German Wanderlust has built up Brandenburg's hiking trail network for the better part of a century." },
  { german: "Zeitgeist", literal: "time-spirit", meaning: "the defining mood or ideas of a specific era", example: "Berlin in the 1920s became shorthand for an entire Zeitgeist that historians still chase." },
  { german: "Doppelgänger", literal: "double-goer", meaning: "a look-alike, often eerily so", example: "Berlin has at least three working Angela Merkel Doppelgänger — they cluster around Brandenburg Gate." },
  { german: "Zeitumstellung", literal: "time-changeover", meaning: "the clocks-forward/back ritual, hated by all Germans equally", example: "Zeitumstellung debate is annual in the Bundestag and goes nowhere, like most clock-related arguments." },
  { german: "Brückentag", literal: "bridge-day", meaning: "the workday between a public holiday and the weekend, often taken as vacation", example: "Take your Brückentage early — by April everyone's already booked them." },
  { german: "Bandscheibenvorfall", literal: "spine-disc-incident", meaning: "a herniated disc", example: "A common German doctor's-note diagnosis after 6 months of working from a kitchen chair." },
  { german: "Krankschreibung", literal: "sick-writing", meaning: "the doctor's sick note — your legal protection from work", example: "Germans use Krankschreibung without shame; calling in sick without it is what's frowned on." },
  { german: "Reisefieber", literal: "travel-fever", meaning: "the anxious excitement before a trip", example: "Reisefieber peaks the night before, when you suddenly can't remember if you packed the passport." },
  { german: "Vorfreude", literal: "fore-joy", meaning: "the anticipation that's sweeter than the event itself", example: "\"Vorfreude ist die schönste Freude\" — translates as \"anticipation is the best joy.\"" },
  { german: "Lebensmüde", literal: "life-tired", meaning: "weary of life — used casually, like \"reckless\"", example: "\"Bist du lebensmüde?\" — \"Are you tired of life?\" — what a friend says when you cross against the red Ampelmann." },
  { german: "Ampelmann", literal: "traffic-light-man", meaning: "the East German pedestrian light figure — kept after reunification, now iconic", example: "The Ampelmann gift shop in Mitte makes more from tourists than any actual crosswalk does in safety." },
  { german: "Ostalgie", literal: "east-nostalgia", meaning: "nostalgia for East German (GDR) life", example: "Ostalgie shops still sell DDR-era cola, mustard, and TV shows. Some genuine, some kitsch." },
  { german: "Wessi / Ossi", literal: "Westerner / Easterner", meaning: "informal terms for people from former West / East Germany", example: "35 years after reunification, Wessi/Ossi still surfaces in conversations — not always politely." },
  { german: "Hartz IV", literal: "(name of reform)", meaning: "unemployment benefit, replaced by Bürgergeld in 2023 — still in vocabulary", example: "Older Berliners still say \"Hartz IV\" even though the official name changed two years ago." },
  { german: "Bürgergeld", literal: "citizen-money", meaning: "the current unemployment benefit", example: "Bürgergeld replaced Hartz IV in 2023 with slightly higher rates and gentler terminology." },
  { german: "Kindergeld", literal: "child-money", meaning: "monthly government payment per child until 18 (or 25 if studying)", example: "Kindergeld is €250/month per child. Apply through the Familienkasse the moment you arrive." },
  { german: "Elterngeld", literal: "parent-money", meaning: "parental leave pay — up to 14 months total, split between parents", example: "Elterngeld replaces 65% of your previous net salary, capped at €1,800/month." },
  { german: "Mutterschutz", literal: "mother-protection", meaning: "the protected leave around childbirth — 6 weeks before, 8 weeks after", example: "Mutterschutz is paid and your job is legally protected." },
  { german: "Kita", literal: "abbreviation for Kindertagesstätte", meaning: "daycare / kindergarten for under-6s", example: "Kita waitlists in Berlin can be 12+ months. Apply when you announce the pregnancy." },
  { german: "Hort", literal: "shelter/refuge", meaning: "after-school care for school-age kids", example: "Hort runs from end-of-school until 17:00, covering working-parent gap years." },
  { german: "Einschulung", literal: "in-schooling", meaning: "the first day of school — a major ceremony", example: "Einschulung includes the Zuckertüte — a cone of candy and small gifts handed to each new first-grader." },
  { german: "Zuckertüte", literal: "sugar-bag", meaning: "the candy/gift cone given to children on their first day of school", example: "Zuckertüte traditions vary by family — some include school supplies, others go full chocolate." },
  { german: "Schultüte", literal: "school-bag", meaning: "alternative name for Zuckertüte", example: "Same item, different region. Both terms work." },
  { german: "Abitur", literal: "abitur (Latin: to depart)", meaning: "the high school exit exam — required for university", example: "Berlin Abitur is on a four-point grading system (1.0 best, 4.0 worst). Sub-1.5 opens any university door." },
  { german: "Numerus Clausus", literal: "limited number (Latin)", meaning: "the GPA cutoff for restricted university programs", example: "Medical school NC in Berlin sits at around 1.0 — meaning straight A's are barely competitive." },
  { german: "Praktikum", literal: "practical work", meaning: "an internship — paid or unpaid", example: "German Praktikum culture is intense — many are 6 months long and treated like real jobs." },
  { german: "Ausbildung", literal: "out-building / formation", meaning: "vocational training program — 2-3 years, mixing school and work", example: "Ausbildung culture is why Germany has skilled electricians who studied for 3 years." },
  { german: "Beamter", literal: "civil servant", meaning: "tenured government employee — practically impossible to fire", example: "Berlin Bürgeramt employees are mostly Beamte. Patience is required from both sides." },
  { german: "Lehrer", literal: "teacher", meaning: "school teacher — typically a Beamter in Berlin", example: "Berlin teachers in 2026 are still on civil-servant track, unlike most other German states." },
  { german: "Bundestag", literal: "federal day-meeting", meaning: "the German federal parliament", example: "Bundestag sessions are public — you can attend with passport ID, often without booking." },
  { german: "Abgeordnetenhaus", literal: "deputies' house", meaning: "the Berlin state parliament — Berlin is also a federal state (Bundesland)", example: "Abgeordnetenhaus elections happen every 5 years; the next one is in 2026." },
  { german: "Bezirk", literal: "district", meaning: "one of Berlin's 12 administrative districts", example: "Each Bezirk has its own Bürgermeister and council — Berlin is more federal than people realize." },
  { german: "Senat", literal: "senate", meaning: "Berlin's state-level government cabinet", example: "The Berlin Senat sits in the Rotes Rathaus and runs the city like its own mini-country." },
  { german: "Verkehrsverbund", literal: "transit-association", meaning: "the umbrella body coordinating regional transport tickets", example: "The VBB Verkehrsverbund covers Berlin, Brandenburg, and most regional trains on one ticket." },
  { german: "Deutschlandticket", literal: "Germany-ticket", meaning: "the €58/month nationwide public transport flat-rate", example: "Deutschlandticket replaced the chaos of regional tickets in 2023. It's the best transit deal in Europe." },
  { german: "Sozialversicherung", literal: "social insurance", meaning: "the umbrella term for health, pension, unemployment, and care insurance", example: "Sozialversicherung deductions are roughly 20% of your gross salary." },
  { german: "Rentenversicherung", literal: "pension insurance", meaning: "the state pension scheme", example: "Rentenversicherung pays around 47% of your last net salary when you retire. Most people supplement." },
  { german: "GEZ-Gebühr", literal: "GEZ fee", meaning: "the public broadcasting fee — €18.36/month per household, no opt-out", example: "GEZ funds ARD, ZDF, and Deutschlandfunk. You pay it whether you own a TV or not." },
  { german: "Rundfunkbeitrag", literal: "broadcasting contribution", meaning: "the official name for the GEZ-Gebühr", example: "Same fee, friendlier name. Still €18.36/month." },
  { german: "Versicherung", literal: "insurance", meaning: "insurance — Germans have a famous obsession with it", example: "Haftpflichtversicherung (liability) is the one absolutely everyone needs." },
  { german: "Haftpflichtversicherung", literal: "liability insurance", meaning: "personal liability insurance — €5-7/month, indispensable", example: "If you break a friend's expensive thing, Haftpflicht covers it. Get it on day one." },
  { german: "Rechtsschutzversicherung", literal: "legal-protection insurance", meaning: "legal insurance — covers lawyer fees for disputes", example: "Rechtsschutz especially useful for renters in Berlin where landlord disputes are common." },
  { german: "Riester-Rente", literal: "Riester pension (name)", meaning: "a state-subsidized private pension scheme", example: "Riester-Rente has tax advantages but limited returns. Often debated, often misunderstood." },
  { german: "Bafög", literal: "abbreviation for student loan act", meaning: "the federal student financial aid", example: "Half the Bafög is a grant, half is a 0% loan capped at €10,000 total." },
  { german: "Wohnberechtigungsschein", literal: "living-entitlement certificate", meaning: "the document showing you qualify for subsidized housing", example: "WBS unlocks roughly 100,000 affordable apartments in Berlin — most people don't know they qualify." },
  { german: "Sozialwohnung", literal: "social housing", meaning: "subsidized affordable housing — Berlin has ~100,000 of these", example: "Sozialwohnung waitlists are long but real — apply early through the Bezirksamt." },
  { german: "Schrippe", literal: "Berlin word for bread roll", meaning: "the standard Berlin breakfast roll", example: "In Munich it's a Semmel. In Berlin it's a Schrippe. They are not the same and Berliners will tell you so." },
  { german: "Pfannkuchen", literal: "pan-cake", meaning: "in Berlin: jelly-filled donut (elsewhere: a pancake)", example: "Order a Pfannkuchen in Berlin, you get a donut. Order one in Munich, you get a pancake. Always confusing." },
  { german: "Berliner", literal: "Berliner", meaning: "JFK's word for the Berlin donut — but also the city's inhabitants", example: "Outside Berlin, what Berliners call Pfannkuchen is called a Berliner. Confusing on purpose." },
  { german: "Currywurst", literal: "curry sausage", meaning: "Berlin's signature sausage dish, smothered in curry-ketchup", example: "Berlin claims to eat 70 million Currywurst a year. There's even a museum." },
  { german: "Döner", literal: "döner (Turkish)", meaning: "the Berlin döner kebab — invented or perfected in 1972 Kreuzberg", example: "Berlin has more kebab shops than Istanbul. The math is contested but the food is excellent." },
  { german: "Bier", literal: "beer", meaning: "beer — taken seriously, ordered casually", example: "\"Ein Berliner, bitte\" gets you Berlin-style beer. \"Ein Pils, bitte\" gets you a Pilsner." },
  { german: "Spätkauf", literal: "late-purchase", meaning: "official name for Späti", example: "Spätkauf is the legal term; Späti is what you'll actually say." },
  { german: "Hinterhof", literal: "back-yard", meaning: "the interior courtyard of a Berlin apartment building", example: "Hinterhof flats are quieter than street-facing ones, but get less light. Trade-offs." },
  { german: "Altbau", literal: "old-building", meaning: "pre-WWII apartment buildings with high ceilings and character", example: "Altbau apartments command 20-30% rent premium over Neubau equivalents." },
  { german: "Neubau", literal: "new-building", meaning: "post-WWII or recent construction", example: "Neubau usually means better insulation, faster internet, and fewer surprises." },
  { german: "Plattenbau", literal: "slab-building", meaning: "the prefabricated concrete buildings — usually East Berlin", example: "Plattenbau dominates Marzahn, Hellersdorf, and parts of Lichtenberg. Functional, divisive aesthetically." },
  { german: "Hauseingang", literal: "house-entrance", meaning: "the main door of an apartment building", example: "Most Berlin Hauseingang require both your apartment key AND ringing a specific name. Learn yours." },
  { german: "Klingel", literal: "doorbell", meaning: "doorbell — usually outside the building entrance with all flat names", example: "Make sure your name is on the Klingel within the first week, or your packages will vanish." },
  { german: "Briefkasten", literal: "letter-box", meaning: "mailbox in the building entryway", example: "If your Briefkasten has no name plate, expect Deutsche Post to return-to-sender everything." },
  { german: "Pfandflasche", literal: "deposit-bottle", meaning: "a returnable bottle with the deposit logo", example: "Pfandflaschen go back to any supermarket — the deposit prints on your next receipt." },
  { german: "Mülltrennung", literal: "trash-separation", meaning: "Germany's complex multi-bin waste sorting system", example: "Berlin has at least 5 bin types: paper, plastic, glass (by color), organic, residual. Get it wrong and your Hausmeister will notice." },
  { german: "Gelber Sack", literal: "yellow sack", meaning: "the yellow bag for packaging waste", example: "Gelber Sack pickup is usually weekly. Pickup days vary by district." },
  { german: "Sperrmüll", literal: "bulky-trash", meaning: "the bulky waste pickup — old furniture, mattresses", example: "Sperrmüll pickup is free in Berlin but needs to be scheduled in advance via the BSR." },
  { german: "BSR", literal: "Berliner Stadtreinigung", meaning: "Berlin's trash & cleaning service", example: "BSR runs the orange trucks and street-cleaning. Their puns on truck sides are city legend." },
  { german: "Kehrwoche", literal: "sweep-week", meaning: "the weekly cleaning duty rotated among building tenants (more common in southern Germany)", example: "Less strict in Berlin, but some older buildings still rotate Kehrwoche. Skip it at social risk." },
  { german: "Putzplan", literal: "cleaning-plan", meaning: "the cleaning schedule in shared apartments", example: "Every WG has a Putzplan. Some are spreadsheet-grade, some are a sticky note in disagreement." },
  { german: "Hausordnung", literal: "house-order", meaning: "the building rules — quiet hours, balcony grilling, washing machine times", example: "Hausordnung typically bans laundry on Sundays and noise from 22:00 to 06:00. Take both seriously." },
  { german: "Ruhezeit", literal: "rest-time", meaning: "the legally protected quiet hours — usually 22:00-06:00 and Sundays", example: "Loud Sunday vacuuming can result in genuine police visits. Don't test this." },
  { german: "Quiet Sundays", literal: "Sonntagsruhe", meaning: "Sunday silence — supermarkets closed, drilling banned, parks quiet", example: "Sonntagsruhe makes Sundays feel like a different country. Plan grocery shopping Saturday." },
  { german: "Brot", literal: "bread", meaning: "bread — Germans take it personally", example: "Germany has 3,200+ registered bread varieties. The UNESCO list recognizes the German bread tradition." },
  { german: "Brötchen", literal: "little-bread", meaning: "bread rolls — many regional names exist", example: "What's called Brötchen nationally is called Schrippe in Berlin and Semmel in Munich. Same item, three battles." },
  { german: "Bäckerei", literal: "bakery", meaning: "bakery — usually open from 6am, the social hub of any Kiez", example: "Walk into any Bäckerei before 9am and you'll see your neighbors. Order the Käsebrötchen." },
  { german: "Konditorei", literal: "confectionery", meaning: "a cake-and-pastry shop — distinct from a bakery", example: "Konditorei = cakes, tarts, fancy. Bäckerei = bread, rolls, casual. Don't confuse them." },
  { german: "Frühstück", literal: "early-piece", meaning: "breakfast — usually elaborate, often the largest meal", example: "German Frühstück is a multi-plate event: bread, cheese, cold cuts, eggs, jam, often Sekt on Sundays." },
  { german: "Abendbrot", literal: "evening-bread", meaning: "the German light dinner of bread, cheese, and cold cuts", example: "Abendbrot reflects how much weight Germans put on bread. Dinner can literally just be bread." },
  { german: "Vesper", literal: "vesper", meaning: "the late-afternoon snack — bread, sausage, beer", example: "Vesper sits between lunch and dinner — common in southern Germany, less so in Berlin." },
  { german: "Kaffee und Kuchen", literal: "coffee and cake", meaning: "the afternoon ritual — coffee, cake, conversation, usually around 16:00", example: "Skipping Kaffee und Kuchen with German in-laws is socially equivalent to skipping Christmas." },
  { german: "Schnaps", literal: "schnapps", meaning: "strong alcoholic spirit — often digestive", example: "Order Schnaps after a heavy meal and a German colleague will nod approvingly." },
  { german: "Glühwein", literal: "glow-wine", meaning: "mulled wine — winter market staple", example: "Glühwein is sold at every Berlin Christmas market between November and December for €4-6 a cup." },
  { german: "Weihnachtsmarkt", literal: "Christmas-market", meaning: "the outdoor Christmas market — open through Advent", example: "Berlin runs over 80 Weihnachtsmärkte each year. Each Bezirk has at least one." },
  { german: "Silvester", literal: "Saint Sylvester (Dec 31)", meaning: "New Year's Eve", example: "Berlin Silvester is loud — fireworks legally start at 18:00 and continue till 03:00." },
  { german: "Karneval", literal: "carnival", meaning: "carnival — mostly Cologne; Berlin's version is the Karneval der Kulturen in spring", example: "Karneval der Kulturen in Kreuzberg is Berlin's cultural festival, distinct from Rhineland Karneval." },
  { german: "Schnee", literal: "snow", meaning: "snow — increasingly rare in Berlin winters", example: "Berlin's last White Christmas was 2010. Climate change is visible in local Schnee data." },
  { german: "Glatteis", literal: "smooth-ice", meaning: "black ice — a real winter danger", example: "Berlin sidewalks aren't always salted. Glatteis warnings during DWD weather reports mean watch your step." },
  { german: "Sommerloch", literal: "summer-hole", meaning: "the slow-news period of high summer when Bundestag is in recess", example: "Sommerloch is why German papers run beach photos in August." },
  { german: "Schlagloch", literal: "hit-hole", meaning: "a pothole", example: "Berlin's pothole map is a real publication. Bicycles fall in. Avoid the U-Bahn replacement bus routes during freezing weather." },
  { german: "Stau", literal: "jam/blockage", meaning: "traffic jam", example: "ARD radio reports Stau on autobahns in near-real-time. The A100 inside Berlin always has one." },
  { german: "Hauptverkehrszeit", literal: "main-traffic-time", meaning: "rush hour", example: "Berlin Hauptverkehrszeit on the U7 stretches from 7:30 to 9:30 morning, 16:30 to 19:00 evening." },
  { german: "Stoßstange an Stoßstange", literal: "bumper to bumper", meaning: "bumper-to-bumper traffic", example: "Heard often on radio traffic reports. Now you know." },
  { german: "Klimaanlage", literal: "climate-installation", meaning: "air conditioning — rare in Berlin homes", example: "Klimaanlage is the missing summer luxury. Most flats rely on cross-ventilation and crossed fingers." },
  { german: "Heizung", literal: "heating", meaning: "the heating system — usually central, controlled per radiator", example: "Heizung gets switched on building-wide around October. The Heizung season runs through April." },
  { german: "Stromrechnung", literal: "electricity-bill", meaning: "electricity bill — usually estimated monthly, reconciled annually", example: "Stromrechnung in Germany comes as an annual surprise. Save 10-15% of your monthly estimate." },
  { german: "Stromzähler", literal: "electricity-counter", meaning: "the electricity meter", example: "Photograph your Stromzähler reading on move-in day and move-out day. Save the photos." },
  { german: "Schornsteinfeger", literal: "chimney-sweep", meaning: "the chimney sweep — said to bring luck on New Year's", example: "Modern Berliners rarely have chimneys, but the Schornsteinfeger image still adorns Silvester decorations." },
  { german: "Glück", literal: "luck/happiness", meaning: "luck and happiness as one concept — German is unusually flexible here", example: "\"Viel Glück\" is good luck. \"Glück gehabt\" is got lucky. \"Glücklich sein\" is to be happy. Same root word." },
  { german: "Ausweis", literal: "identification", meaning: "personal ID — required at all times by law for adults", example: "Carry your Ausweis (or Aufenthaltstitel). Police can ID-check anywhere, and they do." },
  { german: "Aufenthaltstitel", literal: "stay-title", meaning: "residence permit", example: "Aufenthaltstitel is the legal status that makes your life in Germany possible. Renew before it expires." },
  { german: "Niederlassungserlaubnis", literal: "settlement-permission", meaning: "permanent residence permit", example: "Niederlassungserlaubnis is the next step up from a normal Aufenthaltstitel — typically eligible after 5 years." },
  { german: "Einbürgerung", literal: "in-citizenship", meaning: "naturalization — German citizenship", example: "Einbürgerung in Germany typically takes 8 years (5 if married to a German), with B1 language and integration test." },
  { german: "Volkshochschule", literal: "people's high school", meaning: "the public adult education program — cheap classes for everything", example: "VHS Berlin offers German classes from €3.50/hour. Best deal in town for learning B1-B2." },
  { german: "Sprachkurs", literal: "language-course", meaning: "a German class", example: "Most Sprachkurs go A1 → A2 → B1 → B2 → C1 → C2. B1 is the citizenship floor." },
  { german: "Goethe-Zertifikat", literal: "Goethe certificate", meaning: "the standardized German language certificate", example: "Goethe B1 is the bureaucratic gold standard. Universities want B2 or C1." },
  { german: "Integration", literal: "integration", meaning: "the official process of cultural & legal integration into German society", example: "Integrationskurs combines 600 hours of German with a culture/civics module." },
  { german: "Heimat", literal: "homeland", meaning: "homeland — a loaded word, mixed connotations", example: "Heimat has politically charged history. Modern usage tries to reclaim it as warmer." },
  { german: "Mut", literal: "courage", meaning: "courage / boldness", example: "\"Hab Mut\" — German way of saying have courage. Useful with bureaucracy." },
  { german: "Geduld", literal: "patience", meaning: "patience — the survival skill", example: "\"Geduld haben\" — having patience — is the most-tested German trait in your first year." },
  { german: "Hektisch", literal: "hectic", meaning: "rushed, frantic — the opposite of gemütlich", example: "Berlin can be hektisch in November when everyone realizes Steuererklärung is due." },
  { german: "Verzicht", literal: "renunciation", meaning: "deliberate going-without", example: "Verzicht is its own ethical concept — choosing less to gain something else." },
  { german: "Genuss", literal: "enjoyment", meaning: "deep, savored enjoyment", example: "Genuss is what you say about good wine, good food, a good walk through Tiergarten in autumn." },
];

function getRandomWord(excludeWords) {
  excludeWords = excludeWords || [];
  var excluded = {};
  excludeWords.forEach(function(w) { excluded[w] = true; });
  var pool = WORDS.filter(function(w) { return !excluded[w.german]; });
  if (pool.length === 0) pool = WORDS;
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = { getRandomWord: getRandomWord, WORDS: WORDS };
